#!/bin/bash

names=("3m_high_tack_spray_adhesive" "advil_liqui_gels" "band_aid_clear_strips" "band_aid_sheer_strips" "blue_clover_baby_toy" "bumblebee_albacore" "campbells_chicken_noodle_soup" "campbells_soup_at_hand_creamy_tomato" "canon_ack_e10_box" "cheez_it_white_cheddar")

for name in ${names[@]}; do
    DATA_PATH=data/preprocessed/bigbird/${name}
    CONFIG_PATH=configs/bigbird/autogenerated/${name}
    CONFIG_PATH_RFF=configs/bigbird/autogenerated_rff/${name}

    EVAL_OUT_DIR=out/bigbird/${name}/ours_extrinsic_large_bs16384_k4096_lr2e-4/test_eval
    EVAL_OUT_DIR_RFF=out/bigbird/${name}/rff_extrinsic_large_bs16384_k4096_lr2e-4/test_eval

    # Perform training
    echo "Training+Evaluating with config $CONFIG_PATH and afterwards $CONFIG_PATH_RFF"
    python train.py $CONFIG_PATH --allow_checkpoint_loading
    python train.py $CONFIG_PATH_RFF --allow_checkpoint_loading

    python eval.py $EVAL_OUT_DIR $CONFIG_PATH $DATA_PATH test
    python eval.py $EVAL_OUT_DIR_RFF $CONFIG_PATH_RFF $DATA_PATH test
done
